spring:
  datasource:
     url: jdbc:mysql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
     username: ${PROD_DB_USERNAME}
     password: ${PROD_DB_PASSWORD}

  sql:
     init:
        mode: always

  jpa:
     hibernate:
       ddl-auto: update
     open-in-view: false
     defer-datasource-initialization: true

cloudinary:
 cloud_name: ${PROD_CLOUDINARY_CLOUD_NAME}
 api_key: ${PROD_CLOUDINARY_API_KEY}
 api_secret: ${PROD_CLOUDINARY_API_SECRET}

aws:
 accessKey: ${PROD_AWS_ACCESS_KEY}
 secretKey: ${PROD_AWS_SECRET_KEY}
 region: ${PROD_AWS_REGION}

app:
  cookie:
    secure: true