app:
    cookie:
        secure: false

security:
    jwt:
        token:
            secret-key: 78890bef4b3eb6d7a35a9c3a6eef51c0bd349055451c3275ee38221dfe95a4b2
            #               expiration: 8640000

cloudinary:
    cloud_name:
    api_key:
    api_secret:

aws:
    accessKey:
    secretKey:
    region:

spring:
    application:
        name: ExploreBG

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 1234
        url: jdbc:mysql://localhost:3306/explore-bg?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC

    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                format_sql: true
        show-sql: false
        open-in-view: false
        defer-datasource-initialization: true
        database: mysql
        database-platform: org.hibernate.dialect.MySQLDialect

    sql:
        init:
            mode: always

    # we don't need to write /api/v1/ for all controllers
    #server:
    #    servlet:
    #        context-path: /api/v1/

    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB

    data:
        redis:
            host: localhost
            port: 6379
#            password: your_redis_password_if_any
            client-type: lettuce
            timeout: 60000
            lettuce:
                pool:
                    enabled: true
                    max-active: 10
                    max-idle: 5
                    min-idle: 1
                    time-between-eviction-runs: 10s